### ISSUE TITLE
Cuadro comparativo 

### ISSUE THREAD

**Issue by EdgarExa** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-EdgarExa#1]
[TIPOS DE TEXTO.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-EdgarExa/files/9626531/TIPOS.DE.TEXTO.pdf)
Edgar Axel Sandoval Hernández

**Comment by josealfredo79** [comment]
Calificacion 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
